# Generated by Django 5.2.15 on 2026-06-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alertevent_source_report"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alertevent",
            new_name="alerts_even_risk_le_0fb535_idx",
            old_name="alerts_ev_level_start_idx",
        ),
    ]
