# Generated by Django 5.2.15 on 2026-06-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0002_radarframe_anomaly_forecaststage_ingestlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="forecaststage",
            new_name="ingest_fore_valid_t_a2eaa7_idx",
            old_name="ingest_fcast_vts_hex_idx",
        ),
        migrations.RenameIndex(
            model_name="forecaststage",
            new_name="ingest_fore_run_ts_76de9a_idx",
            old_name="ingest_fcast_run_ts_idx",
        ),
    ]
