# Generated by Django 5.2.15 on 2026-06-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0002_fsiweights"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="risksnapshot",
            new_name="risk_snapsh_ts_23400f_idx",
            old_name="risk_snap_ts_level_idx",
        ),
        migrations.AlterField(
            model_name="fsiweights",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
