# Generated by Django 5.2.15 on 2026-06-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="floodreport",
            new_name="reports_flo_status_819f41_idx",
            old_name="reports_fr_status_idx",
        ),
        migrations.RenameIndex(
            model_name="floodreport",
            new_name="reports_flo_observe_15cd90_idx",
            old_name="reports_fr_observed_idx",
        ),
        migrations.RenameIndex(
            model_name="floodreport",
            new_name="reports_flo_hex_id_62757a_idx",
            old_name="reports_fr_hex_created_idx",
        ),
    ]
