# Generated by Django 5.2.15 on 2026-07-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_reports_fr_status_idx_reports_flo_status_819f41_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodreport',
            name='party_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
