# Generated by Django 5.2.15 on 2026-06-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="awsobservation",
            new_name="geo_aws_obs_station_f00884_idx",
            old_name="geo_aws_obs_station_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="hexcell",
            new_name="geo_hex_cel_fsi_sco_cb693b_idx",
            old_name="geo_hex_cel_fsi_sco_idx",
        ),
    ]
