# Generated by Django 5.2.15 on 2026-07-26 02:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_rename_geo_aws_obs_station_ts_idx_geo_aws_obs_station_f00884_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(default='Assam', max_length=32)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'geo_district',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='geo_distric_name_c2ca4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talukas', to='geo.district')),
            ],
            options={
                'db_table': 'geo_taluka',
                'ordering': ['district__name', 'name'],
                'indexes': [models.Index(fields=['district', 'name'], name='geo_taluka_distric_1c089d_idx')],
                'constraints': [models.UniqueConstraint(fields=('district', 'name'), name='geo_taluka_district_name_uniq')],
            },
        ),
    ]
